Web Applications/food_blog-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do
    resources :comments
  end
  
  root to: "posts#index"
  
  get '/about', to: 'pages#about'

end

Web Applications/food_blog-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

Web Applications/food_blog-master/app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :post
end

Web Applications/food_blog-master/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :post
end

Web Applications/food_blog-master/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :ingredients
    has_many :comments, dependent: :destroy
    has_many :directions
    
    accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
    
    validates :title, presence: true, length: {minimum: 5}
    validates :body, :photo, presence: true
    has_attached_file   :photo,
                :default_url => "/images/:style/missing.png",
                :url  => ":s3_domain_url",
                :path => "public/photos/:id/:style_:basename.:extension",
                :storage => :fog,
                :fog_credentials => {
                    provider: 'AWS',
                    aws_access_key_id: ENV["AWS_ACCES_KEY_ID"],
                    aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
                },
                fog_directory: ENV["FOG_DIRECTORY"], 
                :styles => { :medium => "640x360>", :thumb => "450x450" }
                
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

Web Applications/food_blog-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Web Applications/food_blog-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Web Applications/food_blog-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))
        
        redirect_to post_path(@post)
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        
        redirect_to post_path(@post)
    
    end
end

Web Applications/food_blog-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
    
    
end

Web Applications/food_blog-master/app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

end

Web Applications/food_blog-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts= Post.all.order('created_at DESC')
    end
    
    def new
        @post= Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def show
        @post=Post.find(params[:id])
    end
 
    def edit
       @post = Post.find(params[:id])
    end
 
    def update
         @post = Post.find(params[:id])
      
        if @post.update(post_params)
             redirect_to @post
        else
          render 'edit'
        end
    end
 
    def destroy
      @post= Post.find(params[:id])
        @post.destroy
     
        redirect_to root_path
    end
 
    private
    def post_params
        params.require(:post).permit(:title, :body, :photo, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end
    
end

Web Applications/food_blog-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Web Applications/food_blog-master/app/helpers/comments_helper.rb
module CommentsHelper
end

Web Applications/food_blog-master/app/helpers/pages_helper.rb
module PagesHelper
end

Web Applications/food_blog-master/app/helpers/passwords_helper.rb
module PasswordsHelper
end

Web Applications/food_blog-master/app/helpers/posts_helper.rb
module PostsHelper
end

Web Applications/food_blog-master/app/views/comments/_comment.html.erb
<div class = "comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body%></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>
    
    
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: "button",
                    data: {confirm: 'Are you Sure?'} %>
                    </p>
                    
</div>

Web Applications/food_blog-master/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :name %> </br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :body %> </br>
        <%= f.text_area :body %>
    </p>
    </br>
    <p>
        <%= f.submit%>
    </p>
    <%end%>

Web Applications/food_blog-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BinaryBites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="brand">
  <%= image_tag("B_B.jpg")%>
  </br>
  Binary Bites
</div>
<nav class="navbar navbar" role="navigation">
      <div class="container-fluid">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
    </button>
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <a href="https://github.com/Drabants?tab=overview&from=2017-01-01&to=2017-01-09">Github</a>
      </li>
    <% if !user_signed_in? %>
    		<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
		<% else %>
		    <li><%= link_to 'New Post', new_post_path %></li>
		    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete)%></li>
    <% end%>
        </ul>
    </div>
      </div>
</nav>

<%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
<footer>
  <!-- Quantcast Tag -->
<script type="text/javascript">
var _qevents = _qevents || [];

(function() {
var elem = document.createElement('script');
elem.src = (document.location.protocol == "https:" ? "https://secure" : "http://edge") + ".quantserve.com/quant.js";
elem.async = true;
elem.type = "text/javascript";
var scpt = document.getElementsByTagName('script')[0];
scpt.parentNode.insertBefore(elem, scpt);
})();

_qevents.push({
qacct:"p-GX-Z9zNjY-YJK"
});
</script>

<noscript>
<div style="display:none;">
<img src="//pixel.quantserve.com/pixel/p-GX-Z9zNjY-YJK.gif" border="0" height="1" width="1" alt="Quantcast"/>
</div>
</noscript>
<!-- End Quantcast tag -->
</footer>
</html>

Web Applications/food_blog-master/app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shelby Drabant | Software Development</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/simple-sidebar-about.css" rel="stylesheet">

</head>

<body>

    <div class="container-fluid">
        <div class="row">
        
        <!-- Page Content -->
                <p class= "col-xs-10 col-xs-offset-1 about">
Welcome to Binary Bites! This is a website I've been making in order to better understand web development and learn Ruby on Rails. Since I enjoy cooking, I thought a little food blog would be perfect. I'm not the world's best chef, but I have made a few things that are edible. My goal is to post at least one new recipe while also adding new changes to the website weekly in order to get better at cooking and web development. Please feel free to sign up and add your own recipes if you wish!
                </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

Web Applications/food_blog-master/app/views/posts/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "btn btn-default form-button"

Web Applications/food_blog-master/app/views/posts/_form.html.haml
= simple_form_for @post, html: { multipart: true } do |f|
	- if @post.errors.any?
		#errors
			%p
				= @post.errors.count
				Prevented this post froms saving
			%ul
				- @post.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :body, input_html: { class: 'form-control' }
		= f.input :photo, input_html: { class: 'form-control' }
		
		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"
			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f:direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"
						
	= f.button :submit, class: "btn btn-primary"

Web Applications/food_blog-master/app/views/posts/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default"

Web Applications/food_blog-master/app/views/posts/edit.html.erb
<h1>Edit your Post</h1>
<div class="page_wrapper">
    <%= render 'form' %>
</div>

Web Applications/food_blog-master/app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class = "container-fluid">
    <div class = "post_wrapper">
    <div class = "row">
        <div class= "col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 panel">
        <h2 class ="title"> <%= link_to post.title, post %></h2>
        <% if post.photo? %>
            <%= image_tag post.photo.url(:medium), :class => "img-responsive" %>
        <% else %>
            Missing image <%= post.id %>
        <% end %>
                <h3 class = "date"> <%= post.created_at.strftime("%B, %d, %Y") %></h3>
        </div>
    </div>
    </div>
    </div>
<% end %>

Web Applications/food_blog-master/app/views/posts/new.html.erb
<div class="page_wrapper">
<h1>Welcome to a new post</h1>


    <%= render 'form' %>
</div>

Web Applications/food_blog-master/app/views/posts/show.html.haml
.main_content
	.row
		.col-md-3
		.col-md-6
			= image_tag @post.photo.url(:medium), class: "img-responsive thumbnail"
	#post_top.row
		.row
		.col-md-6.col-md-offset-3.panel.col-xs-10.col-xs-offset-1
			#recipe_info
				%h1= @post.title
				%p.body= @post.body
		.col-md-3
				

	.row
		.col-md-1
		.col-md-4.panel.col-xs-10.col-xs-offset-1
			#ingredients
				%h2 Ingredients
				%ul
					- @post.ingredients.each do |ingredient|
						%li= ingredient.name\
		.col-md-2
		.col-md-4.panel.col-xs-10.col-xs-offset-1
			#directions
				%h2 Directions
				%ul
					- @post.directions.each do |direction|
						%li= direction.step
	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_post_path, class: "btn btn-default"
				= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"